/** Daily reflections, rotated by day of year. `ar` is optional. */
export const REFLECTIONS = [
  { ar: "فَاذْكُرُونِي أَذْكُرْكُمْ", en: "So remember Me, and I will remember you.", src: "Quran 2:152" },
  { ar: "إِنَّ مَعَ الْعُسْرِ يُسْرًا", en: "Indeed, with hardship comes ease.", src: "Quran 94:6" },
  { ar: "أَلَا بِذِكْرِ اللَّهِ تَطْمَئِنُّ الْقُلُوبُ", en: "Truly, in the remembrance of Allah do hearts find rest.", src: "Quran 13:28" },
  { ar: "وَاسْتَعِينُوا بِالصَّبْرِ وَالصَّلَاةِ", en: "And seek help through patience and prayer.", src: "Quran 2:45" },
  { ar: "إِنَّ الصَّلَاةَ تَنْهَىٰ عَنِ الْفَحْشَاءِ وَالْمُنكَرِ", en: "Indeed, prayer prohibits immorality and wrongdoing.", src: "Quran 29:45" },
  { ar: "لَا يُكَلِّفُ اللَّهُ نَفْسًا إِلَّا وُسْعَهَا", en: "Allah does not burden a soul beyond what it can bear.", src: "Quran 2:286" },
  { ar: "وَإِذَا سَأَلَكَ عِبَادِي عَنِّي فَإِنِّي قَرِيبٌ", en: "And when My servants ask you about Me, indeed I am near.", src: "Quran 2:186" },
  { ar: "وَمَن يَتَوَكَّلْ عَلَى اللَّهِ فَهُوَ حَسْبُهُ", en: "And whoever relies upon Allah, He is sufficient for him.", src: "Quran 65:3" },
  { ar: "لَئِن شَكَرْتُمْ لَأَزِيدَنَّكُمْ", en: "If you are grateful, I will surely increase you.", src: "Quran 14:7" },
  { ar: "إِنَّ اللَّهَ مَعَ الصَّابِرِينَ", en: "Indeed, Allah is with the patient.", src: "Quran 2:153" },
  { ar: "حَافِظُوا عَلَى الصَّلَوَاتِ وَالصَّلَاةِ الْوُسْطَىٰ", en: "Guard strictly the prayers, and the middle prayer.", src: "Quran 2:238" },
  { ar: "لَا تَقْنَطُوا مِن رَّحْمَةِ اللَّهِ", en: "Do not despair of the mercy of Allah.", src: "Quran 39:53" },
  { ar: "وَهُوَ مَعَكُمْ أَيْنَ مَا كُنتُمْ", en: "And He is with you wherever you are.", src: "Quran 57:4" },
  { ar: "رَبِّ زِدْنِي عِلْمًا", en: "My Lord, increase me in knowledge.", src: "Quran 20:114" },
  { ar: "وَقُولُوا لِلنَّاسِ حُسْنًا", en: "And speak to people good words.", src: "Quran 2:83" },
  { ar: "إِنَّ اللَّهَ لَا يُضِيعُ أَجْرَ الْمُحْسِنِينَ", en: "Indeed, Allah does not allow the reward of those who do good to be lost.", src: "Quran 9:120" },
  { ar: "وَنَحْنُ أَقْرَبُ إِلَيْهِ مِنْ حَبْلِ الْوَرِيدِ", en: "And We are closer to him than his jugular vein.", src: "Quran 50:16" },
  { ar: "ادْعُونِي أَسْتَجِبْ لَكُمْ", en: "Call upon Me; I will respond to you.", src: "Quran 40:60" },
  { ar: "إِنَّ اللَّهَ يُحِبُّ الْمُحْسِنِينَ", en: "Indeed, Allah loves those who do good.", src: "Quran 2:195" },
  { ar: "وَمَا تُقَدِّمُوا لِأَنفُسِكُم مِّنْ خَيْرٍ تَجِدُوهُ عِندَ اللَّهِ", en: "Whatever good you put forward for yourselves, you will find it with Allah.", src: "Quran 2:110" },
  { ar: "فَبِأَيِّ آلَاءِ رَبِّكُمَا تُكَذِّبَانِ", en: "So which of the favors of your Lord would you deny?", src: "Quran 55:13" },
  { ar: "وَرَحْمَتِي وَسِعَتْ كُلَّ شَيْءٍ", en: "And My mercy encompasses all things.", src: "Quran 7:156" },
  { ar: "إِنَّ اللَّهَ وَمَلَائِكَتَهُ يُصَلُّونَ عَلَى النَّبِيِّ", en: "Indeed, Allah and His angels send blessings upon the Prophet.", src: "Quran 33:56" },
  { ar: "وَأَقِمِ الصَّلَاةَ لِذِكْرِي", en: "And establish prayer for My remembrance.", src: "Quran 20:14" },
  { ar: "قَدْ أَفْلَحَ الْمُؤْمِنُونَ ۝ الَّذِينَ هُمْ فِي صَلَاتِهِمْ خَاشِعُونَ", en: "Successful indeed are the believers, those who are humble in their prayers.", src: "Quran 23:1-2" },
  { ar: "وَلَسَوْفَ يُعْطِيكَ رَبُّكَ فَتَرْضَىٰ", en: "And your Lord is going to give you, and you will be satisfied.", src: "Quran 93:5" },
  { ar: "مَن جَاءَ بِالْحَسَنَةِ فَلَهُ عَشْرُ أَمْثَالِهَا", en: "Whoever comes with a good deed will have ten times its like.", src: "Quran 6:160" },
  { ar: "إِنَّ اللَّهَ لَا يُغَيِّرُ مَا بِقَوْمٍ حَتَّىٰ يُغَيِّرُوا مَا بِأَنفُسِهِمْ", en: "Allah will not change the condition of a people until they change what is in themselves.", src: "Quran 13:11" },
  { ar: "وَاصْبِرْ فَإِنَّ اللَّهَ لَا يُضِيعُ أَجْرَ الْمُحْسِنِينَ", en: "And be patient, for indeed Allah does not allow the reward of the good-doers to be lost.", src: "Quran 11:115" },
  { ar: "وَتَزَوَّدُوا فَإِنَّ خَيْرَ الزَّادِ التَّقْوَىٰ", en: "And take provisions, but indeed the best provision is taqwa.", src: "Quran 2:197" },
  { ar: "هَلْ جَزَاءُ الْإِحْسَانِ إِلَّا الْإِحْسَانُ", en: "Is the reward for good anything but good?", src: "Quran 55:60" },
  { ar: "إِنَّ الْحَسَنَاتِ يُذْهِبْنَ السَّيِّئَاتِ", en: "Indeed, good deeds do away with misdeeds.", src: "Quran 11:114" },
  { ar: "وَالَّذِينَ جَاهَدُوا فِينَا لَنَهْدِيَنَّهُمْ سُبُلَنَا", en: "And those who strive for Us, We will surely guide them to Our ways.", src: "Quran 29:69" },
  { ar: "رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ", en: "Our Lord, give us good in this world and good in the Hereafter, and protect us from the punishment of the Fire.", src: "Quran 2:201" },
  { ar: "وَعَسَىٰ أَن تَكْرَهُوا شَيْئًا وَهُوَ خَيْرٌ لَّكُمْ", en: "Perhaps you dislike a thing and it is good for you.", src: "Quran 2:216" },
  { ar: "إِنَّمَا الْأَعْمَالُ بِالنِّيَّاتِ", en: "Actions are only judged by intentions.", src: "Sahih al-Bukhari 1" },
  { ar: "أَحَبُّ الْأَعْمَالِ إِلَى اللَّهِ أَدْوَمُهَا وَإِنْ قَلَّ", en: "The most beloved deeds to Allah are those done consistently, even if small.", src: "Sahih al-Bukhari 6464" },
  { en: "The first thing the servant will be held accountable for on the Day of Resurrection is the prayer. If it is sound, the rest of his deeds will be sound.", src: "Sunan al-Tirmidhi 413" },
  { en: "Prayer in congregation is twenty-seven degrees better than prayer offered alone.", src: "Sahih al-Bukhari 645" },
  { en: "Whoever sends blessings upon me once, Allah will send blessings upon him tenfold.", src: "Sahih Muslim 408" },
  { en: "Charity does not decrease wealth.", src: "Sahih Muslim 2588" },
  { en: "Whoever forgets a prayer, let him pray it when he remembers it. There is no expiation for it except that.", src: "Sahih al-Bukhari 597" },
  { en: "Take advantage of five before five: your youth before your old age, your health before your sickness, your wealth before your poverty, your free time before your busyness, and your life before your death.", src: "Mustadrak al-Hakim 7846" },
  { en: "Read the Quran, for it will come on the Day of Resurrection as an intercessor for its companions.", src: "Sahih Muslim 804" },
  { en: "The best of you are those who learn the Quran and teach it.", src: "Sahih al-Bukhari 5027" },
  { en: "Two words are light on the tongue, heavy on the scale, and beloved to the Most Merciful: SubhanAllahi wa bihamdihi, SubhanAllahil-Azim.", src: "Sahih al-Bukhari 6406" },
  { en: "Smiling in the face of your brother is charity.", src: "Sunan al-Tirmidhi 1956" },
  { en: "None of you truly believes until he loves for his brother what he loves for himself.", src: "Sahih al-Bukhari 13" },
  { en: "Allah does not look at your appearance or your wealth, but He looks at your hearts and your deeds.", src: "Sahih Muslim 2564" },
  { en: "The strong one is not the one who overcomes people by strength, but the one who controls himself when angry.", src: "Sahih al-Bukhari 6114" },
  { en: "Whoever prays Fajr is under the protection of Allah.", src: "Sahih Muslim 657" },
  { en: "Whoever prays the two cool prayers (Fajr and Asr) will enter Paradise.", src: "Sahih al-Bukhari 574" },
  { en: "Whoever follows a path in pursuit of knowledge, Allah will make easy for him a path to Paradise.", src: "Sahih Muslim 2699" },
  { en: "The religion is ease. No one overburdens himself in religion except that it overcomes him. So aim for what is right, draw near to it, and be glad.", src: "Sahih al-Bukhari 39" },
  { en: "The closest a servant is to his Lord is while he is in prostration, so increase your supplication.", src: "Sahih Muslim 482" },
  { en: "Whoever believes in Allah and the Last Day, let him speak good or remain silent.", src: "Sahih al-Bukhari 6018" },
  { en: "Whoever fasts Ramadan out of faith and seeking reward, his previous sins will be forgiven.", src: "Sahih al-Bukhari 38" },
  { en: "The five daily prayers are like a great river running by your door, in which you bathe five times a day.", src: "Sahih Muslim 668" },
  { en: "Be in this world as though you were a stranger or a traveler.", src: "Sahih al-Bukhari 6416" },
  { en: "Every act of goodness is charity.", src: "Sahih al-Bukhari 6021" },
];

/** Short seerah moments for the Friday reminder and Home card. */
export const SEERAH = [
  "The Prophet ﷺ was born in Makkah in the Year of the Elephant, around 570 CE. His father Abdullah had passed away before his birth.",
  "As a young man he was known in Makkah as al-Amin, the trustworthy, long before revelation came to him.",
  "When the Quraysh disputed who would place the Black Stone, he spread his cloak and had each clan's leader lift a corner together.",
  "The first revelation came in the Cave of Hira: \"Read in the name of your Lord who created.\" (96:1)",
  "Khadijah (ra) comforted him after the first revelation: \"Allah would never disgrace you. You keep ties of kinship and help the weak.\"",
  "Abu Bakr (ra) accepted Islam without hesitation and spent his wealth freeing the oppressed, including Bilal (ra).",
  "Bilal (ra), tortured under the Makkan sun, kept repeating one word: \"Ahad, Ahad\" (One, One).",
  "In the Year of Sorrow, the Prophet ﷺ lost both Khadijah (ra) and his uncle Abu Talib, yet kept calling to Allah with patience.",
  "At Ta'if he was stoned and driven out, and still he prayed that their descendants would worship Allah alone.",
  "On the Night Journey the five daily prayers were given as a gift directly to the Prophet ﷺ.",
  "During the Hijrah, hiding in the Cave of Thawr, he told Abu Bakr (ra): \"Do not grieve, Allah is with us.\" (9:40)",
  "The first thing he built on arriving in Madinah was a masjid, and he carried its bricks with his own hands.",
  "In Madinah he paired each emigrant with a helper from the Ansar as a brother, sharing homes and wealth.",
  "At Badr, 313 believers faced an army three times their size. Before the battle he spent the night in prayer.",
  "At the Treaty of Hudaybiyah he accepted terms that seemed unfavorable. Allah called it \"a clear victory.\" (48:1)",
  "He mended his own clothes, milked his goat, and served his family at home, as Aishah (ra) described.",
  "On entering Makkah in victory he forgave those who had persecuted him: \"Go, for you are free.\"",
  "In his Farewell Sermon he declared that no Arab is superior to a non-Arab, nor white to black, except by taqwa.",
  "Among his final instructions: \"The prayer, the prayer, and those whom your right hands possess.\"",
  "He passed away in Madinah in 11 AH in the arms of Aishah (ra), his last words: \"With the highest companion.\"",
];

function dayOfYear(d) { return Math.floor((d - new Date(d.getFullYear(), 0, 0)) / 864e5); }
export function reflectionFor(d) { return REFLECTIONS[dayOfYear(d) % REFLECTIONS.length]; }
export function seerahFor(d) { return SEERAH[Math.floor(dayOfYear(d) / 7) % SEERAH.length]; }
